### PR TITLE
WIP: Add support for private channels

### PR DESCRIPTION
**Pull request by ja5087**
In consideration of security issues raised in #52 this feature will need some careful testing. However it would be useful to let the bot also mirror private channels (e.g. for testing) if we can secure it properly.

### CODE REVIEW

**Comment by dkess** [comment]
I'm not sure if this is desirable, for a few reasons:

* The controls for privacy on IRC are different from Slack, and IRC users aren't visible to Slack users. So if IRC users get added, people on the Slack side might not notice.
* Root staffers can, in theory, use their power to look at IRC messages. Such power is not available to Slack admins. We use private channels incredibly sparingly, so when they do exist, we really want to be certain that their contents are truly secret. Adding an IRC bridge significantly complicates that security model.

We've also spent the last few years moving away from private spaces (like the #star-m channel and #root channels) since they're usually not useful for us anyways. While that's not necessarily a reason to go against this (the channels do exist), I think this in combination with the reasons above are enough to convince me that we shouldn't do this.

**Comment by kpengboy** [comment]
FWIW I would be happy to not be dependent on Slack to stay in the loop with private channels.

**Comment by ja5087** [comment]
IMHO slackbridge being able to mirror private channels is not the same thing as mirroring every private Slack channel. The bot only (and technically already) has access to private channels that it's been invited to. We're not giving the bot any extra Slack permissions with this PR. You're already able to invite irc-bridge into any private channel anyway. 

I've personally seen cases where people set up private channels on Slack (e.g. for testing some bot) and would benefit from being able to have slackbridge there also. It'd be a nice feature to have, and will only require small changes in code.

**Comment by dkess** [comment]
Sure, I just question that this could ever have a use case. My point was that if a channel is private, it's probably for good reason (we really want to be sure that only certain people can read it), and having irc bridge makes this guarantee harder to examine.

If people are just testing something, I'm not sure why they'd need a private channel for that, but I suppose that could be a use case if there's a reason here that I'm not seeing.

If you really want to work on this, I'm fine with it being in the codebase, though I'd be wary of using it in sensitive channels, and I'd want to make sure that people understand the risk of putting this in a private channel.

**Comment by kpengboy** [comment]
Use case: I'd like to be able to read #root from IRC

**Comment by cg505** [comment]
Keep in mind that since slackbridge creds are available to all staff on supernova, inviting slackbridge to any private channel effectively means that all of staff can read the contents of that channel (if they try hard enough).

**Comment by cg505** [comment]
Proposal: we have a dev-slackbridge credential available on supernova, and a different "prod" slackbridge credential that is not accessible to general staff. Then, as long as we don't invite the dev-irc-bridge slack bot to a private channel, we should be fine.

I think this would ultimately be a good change and would be willing to work with jaw to resolve any other issues.

**Comment by cg505** [comment]
Addressing @dkess's concerns
>The controls for privacy on IRC are different from Slack, and IRC users aren't visible to Slack users. So if IRC users get added, people on the Slack side might not notice.

Two step solution: 
1. irc-bridge sends a message when people leave or join channels. If this is annoying in places like #rebuild, we can limit this to private channels. However, it is kind of awkward when somebody joins #rebuild, asks a question, and you answer a few minutes later, just to check IRC afterwards and realize they DC'd right after asking.
1. Implement a slack [slash command](https://api.slack.com/slash-commands) /names that will list all the current IRC users in the channel. This is non-trivial (requires an HTTP server) but I'd be willing to help.

> Root staffers can, in theory, use their power to look at IRC messages. Such power is not available to Slack admins. We use private channels incredibly sparingly, so when they do exist, we really want to be certain that their contents are truly secret. Adding an IRC bridge significantly complicates that security model.

I think it's fair to assume root staffers can ultimately do anything OCF, if they really want to. "rootstaff might abuse this" is not a reasonable concern. If privacy is of the utmost concern (aka people with admin privileges at the OCF cannot be trusted to maintain privacy), then these communications should not happen on any OCF infra, including Slack (or any non-P2P encrypted channel, imo). You can also just choose not to invite irc-bridge to your channel.
Also, this is not a significant complication to the existing security model. We already have the ability to send DMs between IRC/Slack, which more or less has the same security implications (root can read these messages, where DMs are generally assumed to be private).

**Comment by cg505** [comment]
One more thought: to make sure this works safely, we should check that the corresponding IRC channel is private before mirroring a private Slack channel.

**Comment by ja5087** [comment]
I'm going to close this since it doesn't seem to be an issue recently

**Comment by cg505** [comment]
I feel like this may be more relevant than ever as more people move to matrix, to be honest. I personally still would like to see this.

**Pull request closed without merging**
